/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package componentepractico12;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.Connection;


/**
 *
 * @author Daniel
 */
public class Ventana extends javax.swing.JFrame {

    Connection conexion;
    String URL = "jdbc:sqlite:";
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        Path rutaDB = Paths.get("src/database/Almacen.db");
        URL += rutaDB.toAbsolutePath();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecioCompra = new javax.swing.JTextField();
        txtPrecioVenta = new javax.swing.JTextField();
        txtCantidadBodega = new javax.swing.JTextField();
        txtCantidadMinima = new javax.swing.JTextField();
        txtCantidadMaxima = new javax.swing.JTextField();
        btnCrearProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtListadoProductos = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        btnVerProductos = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtNuevaCantMax = new javax.swing.JTextField();
        btnUpdateCantMax = new javax.swing.JButton();
        btnRegistrarVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Almacen OnlyTwo");

        jLabel2.setText("Creación de Productos");

        jLabel3.setText("Código");

        jLabel4.setText("Nombre");

        jLabel5.setText("Precio Compra");

        jLabel6.setText("Precio Venta");

        jLabel7.setText("Cantidad Bodega");

        jLabel8.setText("Cantidad Minima");

        jLabel9.setText("Cantidad Maxima");

        btnCrearProducto.setText("CREAR PRODUCTO");
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });

        txtListadoProductos.setColumns(20);
        txtListadoProductos.setRows(5);
        jScrollPane1.setViewportView(txtListadoProductos);

        jLabel10.setText("Listado de Productos");

        btnVerProductos.setText("VER PRODUCTOS");
        btnVerProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerProductosActionPerformed(evt);
            }
        });

        jLabel11.setText("Nueva Cant. Max.");

        btnUpdateCantMax.setText("ACTUALIZAR");
        btnUpdateCantMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCantMaxActionPerformed(evt);
            }
        });

        btnRegistrarVenta.setText("REGISTRAR VENTA");
        btnRegistrarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNuevaCantMax, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnUpdateCantMax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadBodega, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCantidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrearProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVerProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCantidadBodega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtCantidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCrearProducto)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnVerProductos)
                        .addComponent(btnRegistrarVenta)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNuevaCantMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateCantMax))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCamposProductos() {
        // Limpiar los campos
        txtCodigo.setText("");
        txtNombre.setText("");
        txtPrecioCompra.setText("");
        txtPrecioVenta.setText("");
        txtCantidadBodega.setText("");
        txtCantidadMinima.setText("");
        txtCantidadMaxima.setText("");
        
        // Enfocar el cursor en el campo del código
        txtCodigo.requestFocus();
    }
    
    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed
        // TODO add your handling code here:
        try {
            
            // 1. Verificar que toda la información esté diligenciada
            String codigo = txtCodigo.getText();
            String nombre = txtNombre.getText();     
            int precioCompra = Integer.parseInt(txtPrecioCompra.getText());
            int precioVenta = Integer.parseInt(txtPrecioVenta.getText());
            int cantidadBodega = Integer.parseInt(txtCantidadBodega.getText());
            int cantidadMinima = Integer.parseInt(txtCantidadMinima.getText());
            int cantidadMaxima = Integer.parseInt(txtCantidadMaxima.getText());
            
            if(codigo.isBlank() || nombre.isBlank()) {
                JOptionPane.showMessageDialog(this, "Por favor llene todos los campos");
            } else {
                // 2. Abrir la conexión a la BD
                conexion = Conector.crearConexion(URL);
                
                // 3. Crear el query para insertar los registros a la BD
                String sql = "INSERT INTO PRODUCTOS ( CODIGO, NOMBRE, PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_BODEGA, CANTIDAD_MINIMA, CANTIDAD_MAXIMA ) VALUES ( '%1$s', '%2$s', %3$d, %4$d, %5$d, %6$d, %7$d )";
                String query = String.format(sql, codigo, nombre, precioCompra, precioVenta, cantidadBodega, cantidadMinima, cantidadMaxima);
                
                // 4. Crear la sentencia SQL
                Statement sentencia = conexion.createStatement();
                
                // 5. Invocar el SQL
                int filas = sentencia.executeUpdate(query);
                
                if( filas == 1) {
                    JOptionPane.showMessageDialog(this, "Producto registrado exitosamente");
                    limpiarCamposProductos();
                }
                sentencia.close();
                conexion.close();
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Ocurrió un error");
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Los campos numericos son obligatorios. Intente de nuevo.");
        }
    }//GEN-LAST:event_btnCrearProductoActionPerformed

    private void btnVerProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerProductosActionPerformed
        // TODO add your handling code here:
        try {
            // 1. Abrir la conexión a la BD
            conexion = Conector.crearConexion(URL);
            
            // 2. Crear la sentencia
            Statement sentencia = conexion.createStatement();
            
            // 3. Obtener los resultados de la sentencia SQL
            ResultSet resultados = sentencia.executeQuery("SELECT * FROM PRODUCTOS");
            
            // 4. Recorrer los resultados
            txtListadoProductos.setText("");
            while (resultados.next()) {
                int codigo = resultados.getInt("CODIGO");
                String nombre = resultados.getString("NOMBRE");
                int precioCompra = resultados.getInt("PRECIO_COMPRA");
                int precioVenta = resultados.getInt("PRECIO_VENTA");
                int cantidadBodega = resultados.getInt("CANTIDAD_BODEGA");
                int cantidadMinima = resultados.getInt("CANTIDAD_MINIMA");
                int cantidadMaxima = resultados.getInt("CANTIDAD_MAXIMA");
                
                String cadena = "%1$d - %2$s - %3$d - %4$d - %5$d - %6$d - %7$d";
                String linea = String.format(cadena, codigo, nombre, precioCompra, precioVenta, cantidadBodega, cantidadMinima, cantidadMaxima);
                
                // Actualizar el textArea
                String lineas = txtListadoProductos.getText();
                lineas += linea + "\n";
                txtListadoProductos.setText(lineas);
            }
            sentencia.close();
            conexion.close();
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_btnVerProductosActionPerformed

    private void btnUpdateCantMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCantMaxActionPerformed
        // TODO add your handling code here:
        
        // Para todas las filas de la tabla PRODUCTOS
        // La cantidad Maxima va a ser el valor que ingrese en el campo Nueva Cant. Max.
        
        try {
            // 1. Abrir la conexión a la BD
            conexion = Conector.crearConexion(URL);
            
            // 2. Crear la sentencia
            Statement sentencia = conexion.createStatement();
            
            // 3. Crear el SQL
            String sql = "UPDATE PRODUCTOS SET CANTIDAD_MAXIMA = %1$d";
            int nuevaCantMax = Integer.parseInt(txtNuevaCantMax.getText());
            String query = String.format(sql, nuevaCantMax);
            
            // 4. Ejecutar el SQL
            int filas = sentencia.executeUpdate(query);
            
            if (filas >= 1) {
                JOptionPane.showMessageDialog(this, "Cantidades Maximas actualizadas!");
                txtNuevaCantMax.setText("");
                txtNuevaCantMax.requestFocus();
            }
            
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_btnUpdateCantMaxActionPerformed

    private void btnRegistrarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarVentaActionPerformed
        // TODO add your handling code here:
        // 1. Cerrar la ventana Principal
        this.dispose();
        // 2. Abrir la ventana de registro de Venta
        new RegistroVenta().setVisible(true);
    }//GEN-LAST:event_btnRegistrarVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JButton btnRegistrarVenta;
    private javax.swing.JButton btnUpdateCantMax;
    private javax.swing.JButton btnVerProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCantidadBodega;
    private javax.swing.JTextField txtCantidadMaxima;
    private javax.swing.JTextField txtCantidadMinima;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtListadoProductos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNuevaCantMax;
    private javax.swing.JTextField txtPrecioCompra;
    private javax.swing.JTextField txtPrecioVenta;
    // End of variables declaration//GEN-END:variables
}
